// lib/economy/ca/definitions.ts

import type { CalendarIndicatorSet } from "@/lib/economy/types";

export const CA_CALENDAR_SETS: CalendarIndicatorSet = {
  core: [
    {
      slug: "ca-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "ca-core-cpi-yoy",
      label: "Core CPI (YoY)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["Core CPI y/y"],
    },
    {
      slug: "ca-gdp-mom",
      label: "GDP (MoM)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["GDP m/m"],
    },
    {
      slug: "ca-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "ca-employment-change",
      label: "Employment Change",
      units: "level",
      decimals: 0,
      exactNames: ["Employment Change"],
    },
    {
      slug: "ca-participation-rate",
      label: "Participation Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Participation Rate"],
    },
    {
      slug: "ca-boc-rate",
      label: "BoC Rate",
      units: "pct",
      decimals: 2,
      preferred: true,
      exactNames: ["BoC Interest Rate Decision"],
    },
    {
      slug: "ca-retail-sales-mom",
      label: "Retail Sales (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales m/m"],
    },
    {
      slug: "ca-manufacturing-pmi",
      label: "Manufacturing PMI",
      units: "level",
      decimals: 1,
      exactNames: ["S&P Global Manufacturing PMI"],
      aliases: ["manufacturing pmi"],
    },
    {
      slug: "ca-trade-balance",
      label: "Trade Balance",
      units: "level",
      decimals: 0,
      exactNames: ["Trade Balance"],
    },
    {
      slug: "ca-housing-starts",
      label: "Housing Starts",
      units: "level",
      decimals: 0,
      exactNames: ["CMHC Housing Starts"],
    },
    {
      slug: "ca-cftc-cad-net",
      label: "CFTC CAD Non-Commercial Net Positions",
      units: "level",
      decimals: 0,
      exactNames: ["CFTC CAD Non-Commercial Net Positions"],
    },
  ],

  prices: [
    {
      slug: "ca-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "ca-cpi-mom",
      label: "CPI (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI m/m"],
    },
    {
      slug: "ca-core-cpi-yoy",
      label: "Core CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Core CPI y/y"],
    },
    {
      slug: "ca-core-cpi-mom",
      label: "Core CPI (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Core CPI m/m"],
    },
    {
      slug: "ca-common-cpi-yoy",
      label: "Common CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Common CPI y/y"],
    },
    {
      slug: "ca-median-cpi-yoy",
      label: "Median CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Median CPI y/y"],
    },
    {
      slug: "ca-trimmed-cpi-yoy",
      label: "Trimmed CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Trimmed CPI y/y"],
    },
  ],

  growth: [
    {
      slug: "ca-gdp-mom",
      label: "GDP (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP m/m"],
    },
    {
      slug: "ca-gdp-yoy",
      label: "GDP (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP y/y"],
    },
    {
      slug: "ca-gdp-qoq",
      label: "GDP (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP q/q"],
    },
    {
      slug: "ca-retail-sales-mom",
      label: "Retail Sales (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales m/m"],
    },
    {
      slug: "ca-core-retail-sales-mom",
      label: "Core Retail Sales (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Core Retail Sales m/m"],
    },
    {
      slug: "ca-manufacturing-sales-mom",
      label: "Manufacturing Sales (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Manufacturing Sales m/m"],
    },
    {
      slug: "ca-wholesale-trade-mom",
      label: "Wholesale Trade (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Wholesale Trade m/m"],
    },
    {
      slug: "ca-building-permits-mom",
      label: "Building Permits (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Building Permits m/m"],
    },
  ],

  labour: [
    {
      slug: "ca-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "ca-employment-change",
      label: "Employment Change",
      units: "level",
      decimals: 0,
      exactNames: ["Employment Change"],
    },
    {
      slug: "ca-full-time-employment-change",
      label: "Full-Time Employment Change",
      units: "level",
      decimals: 0,
      exactNames: ["Full-Time Employment Change"],
    },
    {
      slug: "ca-part-time-employment-change",
      label: "Part-Time Employment Change",
      units: "level",
      decimals: 0,
      exactNames: ["Part-Time Employment Change"],
    },
    {
      slug: "ca-participation-rate",
      label: "Participation Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Participation Rate"],
    },
  ],

  policy: [
    {
      slug: "ca-boc-rate",
      label: "BoC Rate",
      units: "pct",
      decimals: 2,
      exactNames: ["BoC Interest Rate Decision"],
    },
    {
      slug: "ca-boc-business-outlook",
      label: "BoC Business Outlook Survey",
      units: "level",
      decimals: 1,
      exactNames: ["BoC Business Outlook Survey"],
    },
  ],

  housing: [
    {
      slug: "ca-housing-starts",
      label: "Housing Starts",
      units: "level",
      decimals: 0,
      exactNames: ["CMHC Housing Starts"],
    },
    {
      slug: "ca-building-permits-mom",
      label: "Building Permits (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Building Permits m/m"],
    },
    {
      slug: "ca-new-house-price-index-mom",
      label: "New House Price Index (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["New Housing Price Index m/m"],
    },
  ],
};