// lib/economy/au/definitions.ts

import type { CalendarIndicatorSet } from "@/lib/economy/types";

export const AU_CALENDAR_SETS: CalendarIndicatorSet = {
  core: [
    {
      slug: "au-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "au-trimmed-mean-cpi-yoy",
      label: "Trimmed Mean CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["RBA Trimmed Mean CPI y/y"],
    },
    {
      slug: "au-gdp-qoq",
      label: "GDP (QoQ)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["GDP q/q"],
    },
    {
      slug: "au-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "au-employment-change",
      label: "Employment Change",
      units: "level",
      decimals: 0,
      exactNames: ["Employment Change"],
    },
    {
      slug: "au-wage-price-index-yoy",
      label: "Wage Price Index (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Wage Price Index y/y"],
    },
    {
      slug: "au-rba-rate",
      label: "RBA Rate",
      units: "pct",
      decimals: 2,
      preferred: true,
      exactNames: ["RBA Interest Rate Decision"],
    },
    {
      slug: "au-retail-sales-mom",
      label: "Retail Sales (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales m/m"],
    },
    {
      slug: "au-manufacturing-pmi",
      label: "Manufacturing PMI",
      units: "level",
      decimals: 1,
      exactNames: ["S&P Global Manufacturing PMI"],
      aliases: ["manufacturing pmi"],
    },
    {
      slug: "au-services-pmi",
      label: "Services PMI",
      units: "level",
      decimals: 1,
      exactNames: ["S&P Global Services PMI"],
      aliases: ["services pmi"],
    },
    {
      slug: "au-trade-balance",
      label: "Trade Balance",
      units: "level",
      decimals: 0,
      exactNames: ["Trade Balance"],
    },
    {
      slug: "au-cftc-aud-net-non-commercial",
      label: "CFTC AUD Non-Commercial Net Positions",
      units: "level",
      decimals: 0,
      exactNames: ["CFTC AUD Non-Commercial Net Positions"],
    },
  ],

  prices: [
    {
      slug: "au-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "au-cpi-qoq",
      label: "CPI (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI q/q"],
    },
    {
      slug: "au-trimmed-mean-cpi-yoy",
      label: "Trimmed Mean CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["RBA Trimmed Mean CPI y/y"],
    },
    {
      slug: "au-trimmed-mean-cpi-qoq",
      label: "Trimmed Mean CPI (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["RBA Trimmed Mean CPI q/q"],
    },
    {
      slug: "au-wage-price-index-yoy",
      label: "Wage Price Index (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Wage Price Index y/y"],
    },
    {
      slug: "au-ppi-yoy",
      label: "PPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["PPI y/y"],
    },
  ],

  growth: [
    {
      slug: "au-gdp-qoq",
      label: "GDP (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP q/q"],
    },
    {
      slug: "au-gdp-yoy",
      label: "GDP (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP y/y"],
    },
    {
      slug: "au-retail-sales-mom",
      label: "Retail Sales (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales m/m"],
    },
    {
      slug: "au-building-approvals-mom",
      label: "Building Approvals (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Building Approvals m/m"],
    },
    {
      slug: "au-home-loans-mom",
      label: "Home Loans (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Home Loans m/m"],
    },
    {
      slug: "au-current-account",
      label: "Current Account",
      units: "level",
      decimals: 0,
      exactNames: ["Current Account"],
    },
  ],

  labour: [
    {
      slug: "au-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "au-participation-rate",
      label: "Participation Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Participation Rate"],
    },
    {
      slug: "au-employment-change",
      label: "Employment Change",
      units: "level",
      decimals: 0,
      exactNames: ["Employment Change"],
    },
    {
      slug: "au-full-time-employment-change",
      label: "Full-Time Employment Change",
      units: "level",
      decimals: 0,
      exactNames: ["Full-Time Employment Change"],
    },
    {
      slug: "au-wage-price-index-yoy",
      label: "Wage Price Index (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Wage Price Index y/y"],
    },
  ],

  policy: [
    {
      slug: "au-rba-rate",
      label: "RBA Rate",
      units: "pct",
      decimals: 2,
      exactNames: ["RBA Interest Rate Decision"],
    },
    {
      slug: "au-mi-inflation-expectations",
      label: "MI Inflation Expectations",
      units: "pct",
      decimals: 1,
      exactNames: ["MI Inflation Expectations"],
    },
    {
      slug: "au-rba-private-sector-credit-mom",
      label: "RBA Private Sector Credit (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["RBA Private Sector Credit m/m"],
    },
  ],
};