// lib/economy/uk/definitions.ts

import type { CalendarIndicatorSet } from "@/lib/economy/types";

export const UK_CALENDAR_SETS: CalendarIndicatorSet = {
  core: [
    {
      slug: "uk-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["CPI y/y"],
      aliases: ["consumer price index y/y", "inflation rate y/y"],
    },
    {
      slug: "uk-core-cpi-yoy",
      label: "Core CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Core CPI y/y"],
      aliases: ["core consumer price index y/y"],
    },
    {
      slug: "uk-gdp-mom",
      label: "GDP (MoM)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["GDP m/m"],
      aliases: ["monthly gdp m/m", "gross domestic product m/m"],
    },
    {
      slug: "uk-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["Unemployment Rate"],
      aliases: ["ilo unemployment rate"],
    },
    {
      slug: "uk-average-earnings-regular-yoy",
      label: "Average Earnings Regular Pay (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Average Weekly Earnings, Regular Pay y/y"],
      aliases: ["average weekly earnings regular pay y/y"],
    },
    {
      slug: "uk-boe-rate",
      label: "BoE Rate",
      units: "pct",
      decimals: 2,
      preferred: true,
      exactNames: ["BoE Interest Rate Decision"],
      aliases: ["official bank rate"],
    },
    {
      slug: "uk-retail-sales-mom",
      label: "Retail Sales (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales m/m"],
    },
    {
      slug: "uk-manufacturing-pmi",
      label: "Manufacturing PMI",
      units: "level",
      decimals: 1,
      exactNames: ["S&P Global/CIPS Manufacturing PMI"],
      aliases: ["manufacturing pmi", "global cips manufacturing pmi"],
    },
    {
      slug: "uk-services-pmi",
      label: "Services PMI",
      units: "level",
      decimals: 1,
      exactNames: ["S&P Global/CIPS Services PMI"],
      aliases: ["services pmi", "service pmi", "global cips services pmi"],
    },
    {
      slug: "uk-trade-balance",
      label: "Trade Balance",
      units: "level",
      decimals: 0,
      exactNames: ["Trade Balance"],
      aliases: ["goods trade balance"],
    },
  ],

  prices: [
    {
      slug: "uk-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "uk-cpi-mom",
      label: "CPI (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI m/m"],
    },
    {
      slug: "uk-core-cpi-yoy",
      label: "Core CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Core CPI y/y"],
    },
    {
      slug: "uk-core-cpi-mom",
      label: "Core CPI (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Core CPI m/m"],
    },
    {
      slug: "uk-cpih-yoy",
      label: "CPIH (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPIH y/y"],
    },
    {
      slug: "uk-ppi-input-yoy",
      label: "PPI Input (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["PPI Input y/y"],
    },
    {
      slug: "uk-ppi-output-yoy",
      label: "PPI Output (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["PPI Output y/y"],
    },
  ],

  growth: [
    {
      slug: "uk-gdp-mom",
      label: "GDP (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP m/m"],
    },
    {
      slug: "uk-gdp-3m3m",
      label: "GDP (3m/3m)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP 3m/3m"],
    },
    {
      slug: "uk-gdp-yoy",
      label: "GDP (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP y/y"],
    },
    {
      slug: "uk-industrial-production-yoy",
      label: "Industrial Production (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Industrial Production y/y"],
    },
    {
      slug: "uk-manufacturing-production-yoy",
      label: "Manufacturing Production (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Manufacturing Production y/y"],
    },
    {
      slug: "uk-index-of-services",
      label: "Index of Services",
      units: "level",
      decimals: 1,
      exactNames: ["Index of Services"],
    },
  ],

  labour: [
    {
      slug: "uk-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "uk-claimant-count-change",
      label: "Claimant Count Change",
      units: "level",
      decimals: 0,
      exactNames: ["Claimant Count Change"],
    },
    {
      slug: "uk-employment-change-3m",
      label: "Employment Change (3 months)",
      units: "level",
      decimals: 0,
      exactNames: ["Employment Change 3-months"],
    },
    {
      slug: "uk-average-earnings-total-yoy",
      label: "Average Earnings Total Pay (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Average Weekly Earnings, Total Pay y/y"],
    },
    {
      slug: "uk-average-earnings-regular-yoy",
      label: "Average Earnings Regular Pay (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Average Weekly Earnings, Regular Pay y/y"],
    },
  ],

  policy: [
    {
      slug: "uk-boe-rate",
      label: "BoE Rate",
      units: "pct",
      decimals: 2,
      exactNames: ["BoE Interest Rate Decision"],
    },
    {
      slug: "uk-boe-vote-hike",
      label: "BoE MPC Vote Hike",
      units: "level",
      decimals: 0,
      exactNames: ["BoE MPC Vote Hike"],
    },
    {
      slug: "uk-boe-vote-cut",
      label: "BoE MPC Vote Cut",
      units: "level",
      decimals: 0,
      exactNames: ["BoE MPC Vote Cut"],
    },
    {
      slug: "uk-boe-vote-unchanged",
      label: "BoE MPC Vote Unchanged",
      units: "level",
      decimals: 0,
      exactNames: ["BoE MPC Vote Unchanged"],
    },
  ],
};