// lib/economy/jp/definitions.ts

import type { CalendarIndicatorSet } from "@/lib/economy/types";

export const JP_CALENDAR_SETS: CalendarIndicatorSet = {
  core: [
    {
      slug: "jp-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "jp-core-cpi-yoy",
      label: "Core CPI (YoY)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["Core CPI y/y"],
    },
    {
      slug: "jp-gdp-qoq",
      label: "GDP (QoQ)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["GDP q/q"],
    },
    {
      slug: "jp-industrial-production-mom",
      label: "Industrial Production (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Industrial Production m/m"],
    },
    {
      slug: "jp-retail-sales-yoy",
      label: "Retail Sales (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales y/y"],
    },
    {
      slug: "jp-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "jp-jobs-to-applicants",
      label: "Jobs to Applicants Ratio",
      units: "level",
      decimals: 2,
      exactNames: ["Jobs to Applicants Ratio"],
    },
    {
      slug: "jp-manufacturing-pmi",
      label: "Manufacturing PMI",
      units: "level",
      decimals: 1,
      exactNames: ["au Jibun Bank Manufacturing PMI"],
    },
    {
      slug: "jp-consumer-confidence",
      label: "Consumer Confidence",
      units: "level",
      decimals: 1,
      exactNames: ["Consumer Confidence Index"],
    },
    {
      slug: "jp-trade-balance",
      label: "Trade Balance",
      units: "level",
      decimals: 0,
      exactNames: ["Trade Balance"],
    },
    {
      slug: "jp-boj-rate",
      label: "BoJ Policy Rate",
      units: "pct",
      decimals: 2,
      exactNames: ["BoJ Interest Rate Decision"],
    },
    {
      slug: "jp-cftc-jpy-net",
      label: "CFTC JPY Non-Commercial Net Positions",
      units: "level",
      decimals: 0,
      exactNames: ["CFTC JPY Non-Commercial Net Positions"],
    },
  ],

  prices: [
    {
      slug: "jp-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "jp-core-cpi-yoy",
      label: "Core CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Core CPI y/y"],
    },
    {
      slug: "jp-cpi-ex-food-energy-yoy",
      label: "CPI Ex Food & Energy (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI excl. Food and Energy y/y"],
    },
    {
      slug: "jp-cpi-mom-sa",
      label: "CPI (MoM, SA)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI s.a. m/m"],
    },
    {
      slug: "jp-tokyo-cpi-yoy",
      label: "Tokyo CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Tokyo CPI y/y"],
    },
    {
      slug: "jp-tokyo-core-cpi-yoy",
      label: "Tokyo Core CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Tokyo Core CPI y/y"],
    },
  ],

  growth: [
    {
      slug: "jp-gdp-qoq",
      label: "GDP (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP q/q"],
    },
    {
      slug: "jp-gdp-yoy",
      label: "GDP (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP y/y"],
    },
    {
      slug: "jp-industrial-production-mom",
      label: "Industrial Production (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Industrial Production m/m"],
    },
    {
      slug: "jp-industrial-production-yoy",
      label: "Industrial Production (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Industrial Production y/y"],
    },
    {
      slug: "jp-retail-sales-yoy",
      label: "Retail Sales (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales y/y"],
    },
    {
      slug: "jp-retail-sales-mom",
      label: "Retail Sales (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales m/m"],
    },
  ],

  labour: [
    {
      slug: "jp-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "jp-jobs-to-applicants",
      label: "Jobs to Applicants Ratio",
      units: "level",
      decimals: 2,
      exactNames: ["Jobs to Applicants Ratio"],
    },
    {
      slug: "jp-labor-cash-earnings-yoy",
      label: "Labor Cash Earnings (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Labor Cash Earnings y/y"],
    },
    {
      slug: "jp-real-wage-yoy",
      label: "Real Wage (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Real Wage y/y"],
    },
    {
      slug: "jp-overtime-pay-yoy",
      label: "Overtime Pay (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Overtime Pay y/y"],
    },
  ],

  policy: [
    {
      slug: "jp-boj-rate",
      label: "BoJ Policy Rate",
      units: "pct",
      decimals: 2,
      exactNames: ["BoJ Interest Rate Decision"],
    },
    {
      slug: "jp-boj-bank-lending-yoy",
      label: "BoJ Bank Lending (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["BoJ Bank Lending y/y"],
    },
    {
      slug: "jp-boj-cgpi-yoy",
      label: "BoJ CGPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["BoJ Corporate Goods Price Index y/y"],
    },
    {
      slug: "jp-boj-cspi-yoy",
      label: "BoJ CSPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["BoJ Corporate Services Price Index y/y"],
    },
  ],

  sentiment: [
    {
      slug: "jp-manufacturing-pmi",
      label: "Manufacturing PMI",
      units: "level",
      decimals: 1,
      exactNames: ["au Jibun Bank Manufacturing PMI"],
    },
    {
      slug: "jp-services-pmi",
      label: "Services PMI",
      units: "level",
      decimals: 1,
      exactNames: ["au Jibun Bank Services PMI"],
    },
    {
      slug: "jp-composite-pmi",
      label: "Composite PMI",
      units: "level",
      decimals: 1,
      exactNames: ["au Jibun Bank Composite PMI"],
    },
    {
      slug: "jp-consumer-confidence",
      label: "Consumer Confidence",
      units: "level",
      decimals: 1,
      exactNames: ["Consumer Confidence Index"],
    },
    {
      slug: "jp-economy-watchers-current",
      label: "Economy Watchers Current",
      units: "level",
      decimals: 1,
      exactNames: ["Economy Watchers Index for Current Conditions"],
    },
  ],
};