// lib/economy/nz/definitions.ts

import type { CalendarIndicatorSet } from "@/lib/economy/types";

export const NZ_CALENDAR_SETS: CalendarIndicatorSet = {
  core: [
    {
      slug: "nz-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "nz-gdp-qoq",
      label: "GDP (QoQ)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["GDP q/q"],
    },
    {
      slug: "nz-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "nz-employment-change-qoq",
      label: "Employment Change (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["Employment Change q/q"],
    },
    {
      slug: "nz-rbnz-rate",
      label: "RBNZ Rate",
      units: "pct",
      decimals: 2,
      preferred: true,
      exactNames: ["RBNZ Interest Rate Decision"],
    },
    {
      slug: "nz-retail-sales-qoq",
      label: "Retail Sales (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales q/q"],
    },
    {
      slug: "nz-trade-balance",
      label: "Trade Balance",
      units: "level",
      decimals: 0,
      exactNames: ["Trade Balance"],
    },
    {
      slug: "nz-building-consents-mom",
      label: "Building Consents (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Building Consents m/m"],
    },
    {
      slug: "nz-manufacturing-pmi",
      label: "Manufacturing PMI",
      units: "level",
      decimals: 1,
      exactNames: ["BusinessNZ Manufacturing Index"],
      aliases: ["manufacturing index", "manufacturing pmi"],
    },
    {
      slug: "nz-anz-business-confidence",
      label: "ANZ Business Confidence",
      units: "level",
      decimals: 1,
      exactNames: ["ANZ Business Confidence"],
    },
    {
      slug: "nz-gdt-price-index",
      label: "GDT Price Index",
      units: "level",
      decimals: 1,
      exactNames: ["GDT Price Index"],
    },
    {
      slug: "nz-cftc-nzd-net",
      label: "CFTC NZD Non-Commercial Net Positions",
      units: "level",
      decimals: 0,
      exactNames: ["CFTC NZD Non-Commercial Net Positions"],
    },
  ],

  prices: [
    {
      slug: "nz-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "nz-cpi-qoq",
      label: "CPI (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI q/q"],
    },
    {
      slug: "nz-food-price-index-mom",
      label: "Food Price Index (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Food Price Index m/m"],
    },
    {
      slug: "nz-anz-commodity-price-index-mom",
      label: "ANZ Commodity Price Index (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["ANZ Commodity Price Index m/m"],
    },
    {
      slug: "nz-ppi-input-qoq",
      label: "PPI Input (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["PPI Input q/q"],
    },
    {
      slug: "nz-ppi-output-qoq",
      label: "PPI Output (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["PPI Output q/q"],
    },
  ],

  growth: [
    {
      slug: "nz-gdp-qoq",
      label: "GDP (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP q/q"],
    },
    {
      slug: "nz-gdp-yoy",
      label: "GDP (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP y/y"],
    },
    {
      slug: "nz-retail-sales-qoq",
      label: "Retail Sales (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales q/q"],
    },
    {
      slug: "nz-core-retail-sales-qoq",
      label: "Core Retail Sales (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["Core Retail Sales q/q"],
    },
    {
      slug: "nz-electronic-card-retail-sales-yoy",
      label: "Electronic Card Retail Sales (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Electronic Card Retail Sales y/y"],
    },
    {
      slug: "nz-manufacturing-sales-qoq",
      label: "Manufacturing Sales (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["Manufacturing Sales q/q"],
    },
  ],

  labour: [
    {
      slug: "nz-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "nz-employment-change-qoq",
      label: "Employment Change (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["Employment Change q/q"],
    },
    {
      slug: "nz-participation-rate",
      label: "Participation Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Participation Rate"],
    },
    {
      slug: "nz-labor-cost-index-qoq",
      label: "Labor Cost Index (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["Labor Cost Index q/q"],
    },
    {
      slug: "nz-labor-cost-index-yoy",
      label: "Labor Cost Index (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Labor Cost Index y/y"],
    },
  ],

  policy: [
    {
      slug: "nz-rbnz-rate",
      label: "RBNZ Rate",
      units: "pct",
      decimals: 2,
      exactNames: ["RBNZ Interest Rate Decision"],
    },
    {
      slug: "nz-rbnz-2y-inflation-expectations",
      label: "RBNZ 2Y Inflation Expectations",
      units: "pct",
      decimals: 1,
      exactNames: ["RBNZ 2-Year Inflation Expectations"],
    },
    {
      slug: "nz-rbnz-nonresident-debt-holdings",
      label: "RBNZ Non-Resident Debt Holdings",
      units: "level",
      decimals: 0,
      exactNames: ["RBNZ Non-Resident Debt Holdings"],
    },
  ],

  sentiment: [
    {
      slug: "nz-manufacturing-pmi",
      label: "Manufacturing PMI",
      units: "level",
      decimals: 1,
      exactNames: ["BusinessNZ Manufacturing Index"],
    },
    {
      slug: "nz-services-index",
      label: "Services Index",
      units: "level",
      decimals: 1,
      exactNames: ["BusinessNZ Services Index"],
    },
    {
      slug: "nz-anz-business-confidence",
      label: "ANZ Business Confidence",
      units: "level",
      decimals: 1,
      exactNames: ["ANZ Business Confidence"],
    },
    {
      slug: "nz-anz-activity-outlook",
      label: "ANZ Activity Outlook",
      units: "level",
      decimals: 1,
      exactNames: ["ANZ Activity Outlook"],
    },
    {
      slug: "nz-consumer-confidence",
      label: "Consumer Confidence",
      units: "level",
      decimals: 1,
      exactNames: ["Westpac McDermott Miller Consumer Confidence"],
    },
  ],
};