// lib/economy/eu/definitions.ts

import type { CalendarIndicatorSet } from "@/lib/economy/types";

export const EU_CALENDAR_SETS: CalendarIndicatorSet = {
  core: [
    {
      slug: "eu-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "eu-core-cpi-yoy",
      label: "Core CPI (YoY)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["Core CPI y/y"],
    },
    {
      slug: "eu-gdp-qoq",
      label: "GDP (QoQ)",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["GDP q/q"],
    },
    {
      slug: "eu-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      preferred: true,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "eu-ecb-rate",
      label: "ECB Main Rate",
      units: "pct",
      decimals: 2,
      preferred: true,
      exactNames: ["ECB Interest Rate Decision"],
    },
    {
      slug: "eu-ecb-deposit-rate",
      label: "ECB Deposit Rate",
      units: "pct",
      decimals: 2,
      exactNames: ["ECB Deposit Facility Rate Decision"],
    },
    {
      slug: "eu-retail-sales-mom",
      label: "Retail Sales (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales m/m"],
    },
    {
      slug: "eu-industrial-production-mom",
      label: "Industrial Production (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Industrial Production m/m"],
    },
    {
      slug: "eu-manufacturing-pmi",
      label: "Manufacturing PMI",
      units: "level",
      decimals: 1,
      exactNames: ["S&P Global Manufacturing PMI"],
      aliases: ["manufacturing pmi"],
    },
    {
      slug: "eu-services-pmi",
      label: "Services PMI",
      units: "level",
      decimals: 1,
      exactNames: ["S&P Global Services PMI"],
      aliases: ["services pmi"],
    },
    {
      slug: "eu-trade-balance",
      label: "Trade Balance",
      units: "level",
      decimals: 0,
      exactNames: ["Trade Balance"],
    },
    {
      slug: "eu-cftc-eur-net-non-commercial",
      label: "CFTC EUR Non-Commercial Net Positions",
      units: "level",
      decimals: 0,
      exactNames: ["CFTC EUR Non-Commercial Net Positions"],
    },
  ],

  prices: [
    {
      slug: "eu-cpi-yoy",
      label: "CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI y/y"],
    },
    {
      slug: "eu-cpi-mom",
      label: "CPI (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["CPI m/m"],
    },
    {
      slug: "eu-core-cpi-yoy",
      label: "Core CPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Core CPI y/y"],
    },
    {
      slug: "eu-core-cpi-mom",
      label: "Core CPI (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Core CPI m/m"],
    },
    {
      slug: "eu-ppi-yoy",
      label: "PPI (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["PPI y/y"],
    },
    {
      slug: "eu-ppi-mom",
      label: "PPI (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["PPI m/m"],
    },
  ],

  growth: [
    {
      slug: "eu-gdp-qoq",
      label: "GDP (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP q/q"],
    },
    {
      slug: "eu-gdp-yoy",
      label: "GDP (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["GDP y/y"],
    },
    {
      slug: "eu-retail-sales-mom",
      label: "Retail Sales (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales m/m"],
    },
    {
      slug: "eu-retail-sales-yoy",
      label: "Retail Sales (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Retail Sales y/y"],
    },
    {
      slug: "eu-industrial-production-mom",
      label: "Industrial Production (MoM)",
      units: "pct",
      decimals: 1,
      exactNames: ["Industrial Production m/m"],
    },
    {
      slug: "eu-industrial-production-yoy",
      label: "Industrial Production (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Industrial Production y/y"],
    },
  ],

  labour: [
    {
      slug: "eu-unemployment-rate",
      label: "Unemployment Rate",
      units: "pct",
      decimals: 1,
      exactNames: ["Unemployment Rate"],
    },
    {
      slug: "eu-employment-change-qoq",
      label: "Employment Change (QoQ)",
      units: "pct",
      decimals: 1,
      exactNames: ["Employment Change q/q"],
    },
    {
      slug: "eu-employment-change-yoy",
      label: "Employment Change (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Employment Change y/y"],
    },
    {
      slug: "eu-labour-cost-index",
      label: "Labour Cost Index",
      units: "level",
      decimals: 1,
      exactNames: ["Labour Cost Index"],
    },
    {
      slug: "eu-wage-costs-yoy",
      label: "Wage Costs (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["Wage Costs y/y"],
    },
  ],

  policy: [
    {
      slug: "eu-ecb-rate",
      label: "ECB Main Rate",
      units: "pct",
      decimals: 2,
      exactNames: ["ECB Interest Rate Decision"],
    },
    {
      slug: "eu-ecb-deposit-rate",
      label: "ECB Deposit Rate",
      units: "pct",
      decimals: 2,
      exactNames: ["ECB Deposit Facility Rate Decision"],
    },
    {
      slug: "eu-ecb-marginal-lending-rate",
      label: "ECB Marginal Lending Rate",
      units: "pct",
      decimals: 2,
      exactNames: ["ECB Marginal Lending Facility Rate Decision"],
    },
    {
      slug: "eu-ecb-m3-money-supply-yoy",
      label: "ECB M3 Money Supply (YoY)",
      units: "pct",
      decimals: 1,
      exactNames: ["ECB M3 Money Supply y/y"],
    },
  ],

  sentiment: [
    {
      slug: "eu-consumer-confidence",
      label: "Consumer Confidence",
      units: "level",
      decimals: 1,
      exactNames: ["Consumer Confidence Index"],
    },
    {
      slug: "eu-economic-sentiment",
      label: "Economic Sentiment",
      units: "level",
      decimals: 1,
      exactNames: ["Economic Sentiment Indicator"],
    },
    {
      slug: "eu-zew-economic-sentiment",
      label: "ZEW Economic Sentiment",
      units: "level",
      decimals: 1,
      exactNames: ["ZEW Economic Sentiment Indicator"],
    },
    {
      slug: "eu-sentix-investor-confidence",
      label: "Sentix Investor Confidence",
      units: "level",
      decimals: 1,
      exactNames: ["Sentix Investor Confidence"],
    },
    {
      slug: "eu-business-climate",
      label: "Business Climate",
      units: "level",
      decimals: 1,
      exactNames: ["Business Climate Indicator"],
    },
  ],
};